export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'


export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const FECTH_TODOS_SUCCESS = "FECTH_TODOS_SUCCESS";
export const FECTH_TODOS_FAIL = "FECTH_TODOS_FAIL";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAIL = "ADD_TODO_FAIL";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_FAIL = "EDIT_TODO_FAIL";
export const COMPLETE_TODO_SUCCESS = "COMPLETE_TODO_SUCCESS";
export const COMPLETE_TODO_FAIL = "COMPLETE_TODO_FAIL";
export const COMPLETE_ALL_SUCCESS = "COMPLETE_ALL_SUCCESS";
export const COMPLETE_ALL_FAIL = "COMPLETE_ALL_FAIL";
export const CLEAR_COMPLETED_SUCCESS = "CLEAR_COMPLETED_SUCCESS";
export const CLEAR_COMPLETED_FAIL = "CLEAR_COMPLETED_FAIL";
